{
 "title": "Backup Controller Dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current Running Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(backup_controller_current_running_backups{})"
    }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(backup_controller_successful_backups{})"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(backup_controller_failed_backups{})"
    }
   ]
  },
  {
   "title": "Backups Successful",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (name) ( backup_controller_successful_backups{} )"
    }
   ]
  },
  {
   "title": "Backups Failed",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (name) ( backup_controller_failed_backups{} )"
    }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "backup_controller_successful_backups{}"
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "backup_controller_failed_backups{}"
    }
   ]
  },
  {
   "title": "Registered Databases",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "backup_controller_registered_databases{}"
    }
   ]
  },
  {
   "title": "Registered Tasks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "backup_controller_registered_cronjobs{}"
    }
   ]
  },
  {
   "title": "Registered Storages",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "backup_controller_registered_storages{}"
    }
   ]
  }
 ]
}