logger:
  level: debug

# Web server configuration
ui:
  enabled: true
  port: 3000
  basePath: /

# Metrics server configuration
metrics:
  enabled: true
  basePath: /
  path: /metrics
  port: 3001

backupper:
  # Storages configuration
  storers:
    # Type of storage. Currently only s3 is available
    s3:
      - name: s3
        endpoint: minio:9000
        region: us-west-1
        bucket: db-backups
        access-key: minio
        client-secret: miniostorage
  # Databases configuration
  exporters:
    # Database types. Currently only postgres is available
    postgres:
      - name: pg
        host: postgres
        port: 5432
        db: postgres
        user: postgres
        password: root
        method:
          type: pg_dump
          options:
            - --insert
  # Cron schedules
  cronjobs:
    - name: pg-backup-task
      # Cron package used: github.com/robfig/cron
      schedule: "* * * * *"
      # Databases to backup
      database:
        name: pg
        type: postgres
      storage:
        name: s3
        type: s3