version: '3'

services:
  backup-controller:
    build:
      dockerfile: Dockerfile
      context: ../..
    environment:
      PGPASSWORD: root    
    volumes:
      - ./backup-controller:/etc/backup-controller
    restart: always
    command: --config /etc/backup-controller/config.yaml
  minio:
    image: minio/minio:RELEASE.2021-12-10T23-03-39Z.fips
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
    volumes:
      - ./minio:/data
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:v2.32.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000